# site settings
title: NBA Data Analysis Project
subtitle: by Dream Big
#email: youremailaddress@gmail.com
description: Advanced Data Science Final Project Website
baseurl:  "/NBAproj" # the subpath of your site, e.g. /blog
url:  "https://advds71x.github.io"  # the base hostname & protocol for your site
author:
street_address: 615 N Wolfe St
city: Baltimore
state: MD
zip_code: 21205
country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url:
github_url: https://github.com/advds71x/NBAproj
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
